### ISSUE TITLE
Careers page integration

### ISSUE THREAD

**Issue by vinodhagan** [AryvartPhpTeam/aryvartnew#10]

**Comment by nivethaRa** [comment]
Started at 10.40

**Comment by nivethaRa** [comment]
Started on 8 Jan 2016 at 10.40 A.M  . Try to finish at 6.30 P.M on the same day .

**Comment by nivethaRa** [comment]
I completed task on 7 P.M  on same day . I face an two issues :
1, in foreach() loop i get only five element .
2. style sheet problem .
